---
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: "make build-release VERSION=${nextRelease.version}"
  - - "@semantic-release/github"
    - assets:
        - path: "dc908_exporter-*.tar.gz"
