name: Go

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
        id: go

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get -y install protobuf-compiler protobuf-compiler-grpc

      - name: Get dependencies
        run: make get-dependencies

      - name: Ensure that all files are properly formatted
        run: |
          FILES=$(go run golang.org/x/tools/cmd/goimports@latest -w -l .)
          if [ -n "${FILES}" ]; then
              printf "Following files are not formatted: \n%s" "$FILES"
              exit 1
          fi

      - name: Test
        run: make test

      - name: Test building
        run: make build
